{
  "formatVersion": "1.1",
  "component": {
    "group": "live.swag.feedutil",
    "module": "feed-util",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.example.feed_util",
          "module": "flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "feed-util-1.0.aar",
          "url": "feed-util-1.0.aar",
          "size": 8411,
          "sha512": "d26ede596ff5482b33ad0759a28814f7057159e1def4c9f058b331e97f8094e7308cc6397c00e2208e3e71a5a54b0b4e112265a3dfb24124c020157488471f0a",
          "sha256": "50d344e3bbfdb82437119ea8834d9f1f2a4a344e0c6e61dad17c1c2203e6a047",
          "sha1": "a33bd6ebbc8f8cbf7fe0849db449f28d392be041",
          "md5": "5ccb239b72f02b6226f2dad184db067a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.example.feed_util",
          "module": "flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "feed-util-1.0.aar",
          "url": "feed-util-1.0.aar",
          "size": 8411,
          "sha512": "d26ede596ff5482b33ad0759a28814f7057159e1def4c9f058b331e97f8094e7308cc6397c00e2208e3e71a5a54b0b4e112265a3dfb24124c020157488471f0a",
          "sha256": "50d344e3bbfdb82437119ea8834d9f1f2a4a344e0c6e61dad17c1c2203e6a047",
          "sha1": "a33bd6ebbc8f8cbf7fe0849db449f28d392be041",
          "md5": "5ccb239b72f02b6226f2dad184db067a"
        }
      ]
    }
  ]
}
