{
  "formatVersion": "1.1",
  "component": {
    "group": "live.swag.feedutil",
    "module": "feed-util",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.example.feed_util",
          "module": "flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "feed-util-1.0.aar",
          "url": "feed-util-1.0.aar",
          "size": 29715,
          "sha512": "4589d36f865aa301462e00fcfcd94b00fdc5985536d3506251c298c5a51e1219fcdc98545f2f056d4bd5ba35c0d4b5cbad1090a986d048613bcf30f575c5ada9",
          "sha256": "18ab5e0f8dc9ffd75d95b7f36dca4421a30e1a86639a5db6b05b22ee6309b8ae",
          "sha1": "c525a347894a25d8d313ce17be4f46c7555500ff",
          "md5": "209e6fc0670a10c4bf13ff6057ec4e8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.example.feed_util",
          "module": "flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "feed-util-1.0.aar",
          "url": "feed-util-1.0.aar",
          "size": 29715,
          "sha512": "4589d36f865aa301462e00fcfcd94b00fdc5985536d3506251c298c5a51e1219fcdc98545f2f056d4bd5ba35c0d4b5cbad1090a986d048613bcf30f575c5ada9",
          "sha256": "18ab5e0f8dc9ffd75d95b7f36dca4421a30e1a86639a5db6b05b22ee6309b8ae",
          "sha1": "c525a347894a25d8d313ce17be4f46c7555500ff",
          "md5": "209e6fc0670a10c4bf13ff6057ec4e8e"
        }
      ]
    }
  ]
}
